Overrode button from nhsuk-frontend, disabled links are rendered as s…
nhs-digital-gp-it-futures/buying-catalogue-components pull request #173
Opened 2021-02-03 16:49 UTC by NickNewlands

Overrode button from nhsuk-frontend, disabled links are rendered as spans

AB#11724

My solution is the most semantically correct, there is no way to actually disable a link as a disabled link is no longer a link technically speaking, it is just text. By removing the 'a' but leaving the 'href', it can easily be transformed back into a link by JS potentially.

An optimal solution would be making the page into a form but this brings with it certain behaviors which might not be desirable.

I have imported and re-written this component from 'nhsuk-frontend':
https://github.com/nhsuk/nhsuk-frontend/tree/master/packages/components/button

If everyone is happy with this PR, I will create the same one against 'nhsuk-frontend' and we will have to add a task to remove this fix when we update the package.

For review, it would be worth comparing the files 'nhsuk-template.njk' against the 'template.njk' in the link provided. I have made the 'element' parameter a bit more flexible and added a test for it.

2021-02-03 16:55 UTC, bjss-andrew approved these changes

2021-02-03 17:15 UTC, bjss-chris requested changes
The actual changes look good but you need to bump up the patch/revision version number.

I tend to use the `npm version` command but you might want to use `--no-git-tag-version`.

It's hardly a major problem but your commit message subject just breaks the recommended 72 character limit and it includes punctuation (the subject is better without). It would be better written in the imperative too, so instead of 'Overrode...' it will be 'Override...'. It's not absolutely essential that you tweak it but also feel free to add a body to your message if it helps. (The body doesn't need to be in the imperative and can include punctuation.)

2021-02-04 09:52 UTC, bjss-chris submitted a review, later dismissed
Can you choose squash and merge and squash to one commit with your tidied message when you merge your PR?

2021-02-04 10:50 UTC, bjss-chris approved these changes

2021-02-04 10:51 UTC, merged